apiVersion: v1
kind: ConfigMap
metadata:
  name: {name}-config
data:
  kibana.yml: |
    server.name: '{name}'
    logging.dest: /etc/kibana/kibana.log
{re.sub('^', '    ', configure, flags=re.M)}
  elasticsearchHosts: "https://elasticsearch-master:9200"
    