apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - name: kibana
        image: {image}        
        ports:
        - containerPort: 5601
          name: kibana
        env:
        - name: KBN_PATH_CONF
          value: /etc/kibana
        volumeMounts:
        - name: config
          mountPath: /etc/kibana
      volumes:
      - name: config
        configMap: 
          name: {name}-config
